
language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
deploy:
 provider: heroku
 api_key: 66f30e5a-160b-4f7f-a6b9-4b9f25d26db7
 app: nameless-sands-26342
 run: "rake db:migrate"
 on:
  all_branches: true